name: Release 🚀

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to be released
        required: true

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/ci.yml
    with:
      build_dist: true

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          release_name: v${{ inputs.version }}
          draft: false
          prerelease: false
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          make_latest: true
          files: dist/*
          overwrite_files: true